-- Code generated by ODKToMySQL
-- -x /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/Pilar_Disponibilidad_Boleta_Comunitaria.xlsx -t maintable -v device_id_3 -f /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/manifest.xml -T /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/iso639.sql -m /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/metadata.sql -I /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/insert.xml -i /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/insert.sql -C /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/create.xml -c /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/create.sql /home/acoto/sesan_repo/acoto/forms/Pilar_Disponibilidad_Boleta_Comunitaria/curbanos.csv 
-- Created: jue. octubre 11 2018 11:30:13 p.m.
-- by: ODKToMySQL Version 1.0
-- WARNING! All changes made in this file might be lost when running ODKToMySQL again

DROP TABLE IF EXISTS maintable;
DROP TABLE IF EXISTS lkpsem_comunidad_totales;
