-- Code generated by ODKToMySQL
-- -x /home/acoto/sesan_repo/acoto/forms/Csacsacsa/Csacsacsa.xlsx -t maintable -v device_id_3 -f /home/acoto/sesan_repo/acoto/forms/Csacsacsa/manifest.xml -T /home/acoto/sesan_repo/acoto/forms/Csacsacsa/iso639.sql -m /home/acoto/sesan_repo/acoto/forms/Csacsacsa/metadata.sql -I /home/acoto/sesan_repo/acoto/forms/Csacsacsa/insert.xml -i /home/acoto/sesan_repo/acoto/forms/Csacsacsa/insert.sql -C /home/acoto/sesan_repo/acoto/forms/Csacsacsa/create.xml -c /home/acoto/sesan_repo/acoto/forms/Csacsacsa/create.sql /home/acoto/sesan_repo/acoto/forms/Csacsacsa/curbanos.csv 
-- Created: vie. septiembre 14 2018 3:55:23 p.m.
-- by: ODKToMySQL Version 1.0
-- WARNING! All changes made in this file might be lost when running ODKToMySQL again

DROP TABLE IF EXISTS maintable_msel_sem_comunidad_totales;
DROP TABLE IF EXISTS maintable;
DROP TABLE IF EXISTS lkpsem_comunidad_totales;
