-- Code generated by ODKToMySQL
-- -x /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/Wwwwwwww.xlsx -t maintable -v device_id_3 -f /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/manifest.xml -T /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/iso639.sql -m /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/metadata.sql -I /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/insert.xml -i /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/insert.sql -C /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/create.xml -c /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/create.sql /home/acoto/sesan_repo/acoto/forms/Wwwwwwww/curbanos.csv 
-- Created: mar. septiembre 25 2018 11:34:52 a.m.
-- by: ODKToMySQL Version 1.0
-- WARNING! All changes made in this file might be lost when running ODKToMySQL again

DROP TABLE IF EXISTS maintable;
DROP TABLE IF EXISTS lkpsem_comunidad_totales;
